Gravando log em: logs/xceptionNet/V1/log_teste_df.txt
Número de imagens (Foren): 11403
Foren classes: {'fake': 0, 'real': 1}
Número de imagens (DF): 9564
DF classes   : {'fake': 0, 'real': 1}
/home/sato/virtualpy/lib/python3.13/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name xception to current legacy_xception.
  model = create_fn(
Acurácia no Teste (DeepfakeFaces): 83.10%
              precision    recall  f1-score   support

        fake       0.83      1.00      0.91      7934
        real       0.66      0.02      0.03      1630

    accuracy                           0.83      9564
   macro avg       0.75      0.51      0.47      9564
weighted avg       0.80      0.83      0.76      9564

Acurácia no Teste (Foren): 52.26%
              precision    recall  f1-score   support

        fake       0.51      0.96      0.67      5697
        real       0.69      0.08      0.15      5706

    accuracy                           0.52     11403
   macro avg       0.60      0.52      0.41     11403
weighted avg       0.60      0.52      0.41     11403

